version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: 'Rip-and-Ship_Mongo'
    restart: always
    ports:
      - '27099:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: HelloThere
